### ISSUE TITLE
8. Discover-the-effect-of-simple-looping-errors.c

### ISSUE THREAD

**Issue by AraSaWCH** [TheSaviourEking/C-Programming-with-Linux-Specialization#1]
Unfortunately, the code you mentioned didn't work :/
I know it may seem a bit dummy but I  changed it to this and scored it worked:
#include <stdio.h>

int main(void) {
    int i;
    printf("+");
    for (i = 0; i < 23; i++)
        printf("-");
    printf("+\n");
    for (i = 0; i < 1; i++)
        printf("| o | X | o | X | o | X | \n");
        printf("\n");
        printf("| X | o | X | o | X | o |");
        printf("\n");
        printf("| o | X | o | X | o | X | \n");
        printf("\n");
        printf("| X | o | X | o | X | o |");
        printf("\n");
        printf("| o | X | o | X | o | X | \n");
        printf("\n");
        printf("| X | o | X | o | X | o |");
        printf("\n");
    printf("+");
    for (i = 0; i < 23; i++)
        printf("-");
    printf("+");
    return(0);
}

**Comment by TheSaviourEking** [comment]
Thanks for bringing this up. After reviewing the code, I found i made a typo. Please check the updated version if it solves your usecase @AraSaWCH .
